ALTER TABLE orders ADD COLUMN IF NOT EXISTS is_locked BOOLEAN DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS locked_date TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS manually_unlocked BOOLEAN DEFAULT FALSE;

